# Generated by Django 5.2.7 on 2026-07-28 18:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('core', '0003_alter_patient_address_alter_patient_age_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('summary', 'AI Summary Generated'), ('diagnosis_suggestion', 'AI Diagnosis Suggested'), ('test_recommendation', 'AI Test Recommended'), ('record_extraction', 'Medical Record Extracted')], max_length=30)),
                ('ai_model', models.CharField(blank=True, default='', max_length=255)),
                ('input_summary', models.TextField(blank=True, default='')),
                ('output_summary', models.TextField(blank=True, default='')),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('blockchain_hash', models.CharField(blank=True, default='', max_length=66)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='agent_type',
            field=models.CharField(choices=[('doctor', 'Doctor Assistant'), ('medical_records', 'Medical Records Agent')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['title'], name='ai_conversa_title_7e1f66_idx'),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai.conversation'),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_audit_trails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai.uploadeddocument'),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.patient'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['action_type'], name='ai_audittra_action__d9013d_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['doctor', 'created_at'], name='ai_audittra_doctor__a9301b_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['patient', 'created_at'], name='ai_audittra_patient_be0ea4_idx'),
        ),
    ]
