/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace BlockedIPRegistry {
  export type BlockEntryStruct = {
    ipHash: BytesLike;
    blockTime: BigNumberish;
    expiryTime: BigNumberish;
    reason: string;
    blockedBy: AddressLike;
    isManual: boolean;
  };

  export type BlockEntryStructOutput = [
    ipHash: string,
    blockTime: bigint,
    expiryTime: bigint,
    reason: string,
    blockedBy: string,
    isManual: boolean
  ] & {
    ipHash: string;
    blockTime: bigint;
    expiryTime: bigint;
    reason: string;
    blockedBy: string;
    isManual: boolean;
  };
}

export interface BlockedIPRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "blockIP"
      | "blockedIPList"
      | "blockedIPs"
      | "cleanupExpiredBlocks"
      | "getBlockEntry"
      | "getBlockedIPCount"
      | "getBlockedIPList"
      | "isBlocked"
      | "isIPBlocked"
      | "unblockIP"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "IPBlocked" | "IPUnblocked"): EventFragment;

  encodeFunctionData(
    functionFragment: "blockIP",
    values: [BytesLike, BigNumberish, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "blockedIPList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "blockedIPs",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cleanupExpiredBlocks",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBlockEntry",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBlockedIPCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBlockedIPList",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isBlocked",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isIPBlocked",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unblockIP",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "blockIP", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "blockedIPList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "blockedIPs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cleanupExpiredBlocks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBlockEntry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBlockedIPCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBlockedIPList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isBlocked", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isIPBlocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unblockIP", data: BytesLike): Result;
}

export namespace IPBlockedEvent {
  export type InputTuple = [
    ipHash: BytesLike,
    blockTime: BigNumberish,
    expiryTime: BigNumberish,
    reason: string,
    isManual: boolean
  ];
  export type OutputTuple = [
    ipHash: string,
    blockTime: bigint,
    expiryTime: bigint,
    reason: string,
    isManual: boolean
  ];
  export interface OutputObject {
    ipHash: string;
    blockTime: bigint;
    expiryTime: bigint;
    reason: string;
    isManual: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IPUnblockedEvent {
  export type InputTuple = [ipHash: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [ipHash: string, timestamp: bigint];
  export interface OutputObject {
    ipHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BlockedIPRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): BlockedIPRegistry;
  waitForDeployment(): Promise<this>;

  interface: BlockedIPRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  blockIP: TypedContractMethod<
    [
      ipHash: BytesLike,
      duration: BigNumberish,
      reason: string,
      manual: boolean
    ],
    [void],
    "nonpayable"
  >;

  blockedIPList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  blockedIPs: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, string, string, boolean] & {
        ipHash: string;
        blockTime: bigint;
        expiryTime: bigint;
        reason: string;
        blockedBy: string;
        isManual: boolean;
      }
    ],
    "view"
  >;

  cleanupExpiredBlocks: TypedContractMethod<[], [void], "nonpayable">;

  getBlockEntry: TypedContractMethod<
    [ipHash: BytesLike],
    [BlockedIPRegistry.BlockEntryStructOutput],
    "view"
  >;

  getBlockedIPCount: TypedContractMethod<[], [bigint], "view">;

  getBlockedIPList: TypedContractMethod<[], [string[]], "view">;

  isBlocked: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  isIPBlocked: TypedContractMethod<[ipHash: BytesLike], [boolean], "view">;

  unblockIP: TypedContractMethod<[ipHash: BytesLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "blockIP"
  ): TypedContractMethod<
    [
      ipHash: BytesLike,
      duration: BigNumberish,
      reason: string,
      manual: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "blockedIPList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "blockedIPs"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, string, string, boolean] & {
        ipHash: string;
        blockTime: bigint;
        expiryTime: bigint;
        reason: string;
        blockedBy: string;
        isManual: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "cleanupExpiredBlocks"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBlockEntry"
  ): TypedContractMethod<
    [ipHash: BytesLike],
    [BlockedIPRegistry.BlockEntryStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBlockedIPCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBlockedIPList"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "isBlocked"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isIPBlocked"
  ): TypedContractMethod<[ipHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "unblockIP"
  ): TypedContractMethod<[ipHash: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "IPBlocked"
  ): TypedContractEvent<
    IPBlockedEvent.InputTuple,
    IPBlockedEvent.OutputTuple,
    IPBlockedEvent.OutputObject
  >;
  getEvent(
    key: "IPUnblocked"
  ): TypedContractEvent<
    IPUnblockedEvent.InputTuple,
    IPUnblockedEvent.OutputTuple,
    IPUnblockedEvent.OutputObject
  >;

  filters: {
    "IPBlocked(bytes32,uint256,uint256,string,bool)": TypedContractEvent<
      IPBlockedEvent.InputTuple,
      IPBlockedEvent.OutputTuple,
      IPBlockedEvent.OutputObject
    >;
    IPBlocked: TypedContractEvent<
      IPBlockedEvent.InputTuple,
      IPBlockedEvent.OutputTuple,
      IPBlockedEvent.OutputObject
    >;

    "IPUnblocked(bytes32,uint256)": TypedContractEvent<
      IPUnblockedEvent.InputTuple,
      IPUnblockedEvent.OutputTuple,
      IPUnblockedEvent.OutputObject
    >;
    IPUnblocked: TypedContractEvent<
      IPUnblockedEvent.InputTuple,
      IPUnblockedEvent.OutputTuple,
      IPUnblockedEvent.OutputObject
    >;
  };
}
