/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace BlockedIPRegistry {
  export type BlockEntryStruct = { ip: string; timestamp: BigNumberish };

  export type BlockEntryStructOutput = [ip: string, timestamp: bigint] & {
    ip: string;
    timestamp: bigint;
  };
}

export interface BlockedIPRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "blockIP" | "blockedIPs" | "getBlockedIPs"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "IPBlocked"): EventFragment;

  encodeFunctionData(functionFragment: "blockIP", values: [string]): string;
  encodeFunctionData(
    functionFragment: "blockedIPs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBlockedIPs",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "blockIP", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "blockedIPs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBlockedIPs",
    data: BytesLike
  ): Result;
}

export namespace IPBlockedEvent {
  export type InputTuple = [ip: string, timestamp: BigNumberish];
  export type OutputTuple = [ip: string, timestamp: bigint];
  export interface OutputObject {
    ip: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BlockedIPRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): BlockedIPRegistry;
  waitForDeployment(): Promise<this>;

  interface: BlockedIPRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  blockIP: TypedContractMethod<[ip: string], [void], "nonpayable">;

  blockedIPs: TypedContractMethod<
    [arg0: BigNumberish],
    [[string, bigint] & { ip: string; timestamp: bigint }],
    "view"
  >;

  getBlockedIPs: TypedContractMethod<
    [],
    [BlockedIPRegistry.BlockEntryStructOutput[]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "blockIP"
  ): TypedContractMethod<[ip: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "blockedIPs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[string, bigint] & { ip: string; timestamp: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBlockedIPs"
  ): TypedContractMethod<
    [],
    [BlockedIPRegistry.BlockEntryStructOutput[]],
    "view"
  >;

  getEvent(
    key: "IPBlocked"
  ): TypedContractEvent<
    IPBlockedEvent.InputTuple,
    IPBlockedEvent.OutputTuple,
    IPBlockedEvent.OutputObject
  >;

  filters: {
    "IPBlocked(string,uint256)": TypedContractEvent<
      IPBlockedEvent.InputTuple,
      IPBlockedEvent.OutputTuple,
      IPBlockedEvent.OutputObject
    >;
    IPBlocked: TypedContractEvent<
      IPBlockedEvent.InputTuple,
      IPBlockedEvent.OutputTuple,
      IPBlockedEvent.OutputObject
    >;
  };
}
