# Generated by Django 5.2.7 on 2026-01-18 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_hash', models.CharField(max_length=66, unique=True)),
                ('pattern_data', models.JSONField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('severity', models.IntegerField()),
                ('ip_count', models.IntegerField()),
                ('request_count', models.IntegerField()),
                ('blockchain_synced', models.BooleanField(default=False)),
                ('signature_tx_hash', models.CharField(blank=True, max_length=66)),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['pattern_hash'], name='firewall_at_pattern_52adc7_idx'), models.Index(fields=['detected_at'], name='firewall_at_detecte_491aa9_idx'), models.Index(fields=['severity'], name='firewall_at_severit_0b9d59_idx'), models.Index(fields=['blockchain_synced'], name='firewall_at_blockch_41d497_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('threat_score', models.IntegerField()),
                ('threat_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('user_agent', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rate_score', models.IntegerField(default=0)),
                ('pattern_score', models.IntegerField(default=0)),
                ('session_score', models.IntegerField(default=0)),
                ('entropy_score', models.IntegerField(default=0)),
                ('auth_failure_score', models.IntegerField(default=0)),
                ('action_taken', models.CharField(max_length=50)),
                ('blocked_on_blockchain', models.BooleanField(default=False)),
                ('block_tx_hash', models.CharField(blank=True, max_length=66)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address'], name='firewall_se_ip_addr_bee7c1_idx'), models.Index(fields=['timestamp'], name='firewall_se_timesta_579fe5_idx'), models.Index(fields=['threat_level'], name='firewall_se_threat__7f6f46_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('ip_hash', models.CharField(max_length=66)),
                ('block_time', models.DateTimeField(auto_now_add=True)),
                ('expiry_time', models.DateTimeField()),
                ('reason', models.TextField()),
                ('is_manual', models.BooleanField(default=False)),
                ('blockchain_synced', models.BooleanField(default=False)),
                ('block_tx_hash', models.CharField(blank=True, max_length=66)),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-block_time'],
                'indexes': [models.Index(fields=['ip_address'], name='firewall_bl_ip_addr_b0bb61_idx'), models.Index(fields=['expiry_time'], name='firewall_bl_expiry__762cbb_idx'), models.Index(fields=['blockchain_synced'], name='firewall_bl_blockch_25ce2a_idx')],
            },
        ),
    ]
