/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AttackSignatureRegistry {
  export type AttackSignatureStruct = {
    signatureHash: BytesLike;
    pattern: string;
    detectedTime: BigNumberish;
    reportedBy: AddressLike;
    severity: BigNumberish;
  };

  export type AttackSignatureStructOutput = [
    signatureHash: string,
    pattern: string,
    detectedTime: bigint,
    reportedBy: string,
    severity: bigint
  ] & {
    signatureHash: string;
    pattern: string;
    detectedTime: bigint;
    reportedBy: string;
    severity: bigint;
  };
}

export interface AttackSignatureRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addSignature"
      | "getAllSignatures"
      | "getSignature"
      | "getSignatureCount"
      | "getSignaturesBySeverity"
      | "hasSignature"
      | "signatureExists"
      | "signatureList"
      | "signatures"
      | "updateSeverity"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AttackSignatureAdded" | "AttackSignatureUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addSignature",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllSignatures",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSignature",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSignatureCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSignaturesBySeverity",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasSignature",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "signatureExists",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "signatureList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "signatures",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSeverity",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllSignatures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSignatureCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSignaturesBySeverity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signatureExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signatureList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "signatures", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateSeverity",
    data: BytesLike
  ): Result;
}

export namespace AttackSignatureAddedEvent {
  export type InputTuple = [
    signatureHash: BytesLike,
    severity: BigNumberish,
    timestamp: BigNumberish,
    reportedBy: AddressLike
  ];
  export type OutputTuple = [
    signatureHash: string,
    severity: bigint,
    timestamp: bigint,
    reportedBy: string
  ];
  export interface OutputObject {
    signatureHash: string;
    severity: bigint;
    timestamp: bigint;
    reportedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AttackSignatureUpdatedEvent {
  export type InputTuple = [
    signatureHash: BytesLike,
    newSeverity: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    signatureHash: string,
    newSeverity: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    signatureHash: string;
    newSeverity: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AttackSignatureRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AttackSignatureRegistry;
  waitForDeployment(): Promise<this>;

  interface: AttackSignatureRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addSignature: TypedContractMethod<
    [pattern: string, severity: BigNumberish],
    [string],
    "nonpayable"
  >;

  getAllSignatures: TypedContractMethod<[], [string[]], "view">;

  getSignature: TypedContractMethod<
    [signatureHash: BytesLike],
    [AttackSignatureRegistry.AttackSignatureStructOutput],
    "view"
  >;

  getSignatureCount: TypedContractMethod<[], [bigint], "view">;

  getSignaturesBySeverity: TypedContractMethod<
    [minSeverity: BigNumberish],
    [string[]],
    "view"
  >;

  hasSignature: TypedContractMethod<
    [signatureHash: BytesLike],
    [boolean],
    "view"
  >;

  signatureExists: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  signatureList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  signatures: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, string, bigint] & {
        signatureHash: string;
        pattern: string;
        detectedTime: bigint;
        reportedBy: string;
        severity: bigint;
      }
    ],
    "view"
  >;

  updateSeverity: TypedContractMethod<
    [signatureHash: BytesLike, newSeverity: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addSignature"
  ): TypedContractMethod<
    [pattern: string, severity: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllSignatures"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getSignature"
  ): TypedContractMethod<
    [signatureHash: BytesLike],
    [AttackSignatureRegistry.AttackSignatureStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSignatureCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSignaturesBySeverity"
  ): TypedContractMethod<[minSeverity: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "hasSignature"
  ): TypedContractMethod<[signatureHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "signatureExists"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "signatureList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "signatures"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, string, bigint] & {
        signatureHash: string;
        pattern: string;
        detectedTime: bigint;
        reportedBy: string;
        severity: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "updateSeverity"
  ): TypedContractMethod<
    [signatureHash: BytesLike, newSeverity: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AttackSignatureAdded"
  ): TypedContractEvent<
    AttackSignatureAddedEvent.InputTuple,
    AttackSignatureAddedEvent.OutputTuple,
    AttackSignatureAddedEvent.OutputObject
  >;
  getEvent(
    key: "AttackSignatureUpdated"
  ): TypedContractEvent<
    AttackSignatureUpdatedEvent.InputTuple,
    AttackSignatureUpdatedEvent.OutputTuple,
    AttackSignatureUpdatedEvent.OutputObject
  >;

  filters: {
    "AttackSignatureAdded(bytes32,uint256,uint256,address)": TypedContractEvent<
      AttackSignatureAddedEvent.InputTuple,
      AttackSignatureAddedEvent.OutputTuple,
      AttackSignatureAddedEvent.OutputObject
    >;
    AttackSignatureAdded: TypedContractEvent<
      AttackSignatureAddedEvent.InputTuple,
      AttackSignatureAddedEvent.OutputTuple,
      AttackSignatureAddedEvent.OutputObject
    >;

    "AttackSignatureUpdated(bytes32,uint256,uint256)": TypedContractEvent<
      AttackSignatureUpdatedEvent.InputTuple,
      AttackSignatureUpdatedEvent.OutputTuple,
      AttackSignatureUpdatedEvent.OutputObject
    >;
    AttackSignatureUpdated: TypedContractEvent<
      AttackSignatureUpdatedEvent.InputTuple,
      AttackSignatureUpdatedEvent.OutputTuple,
      AttackSignatureUpdatedEvent.OutputObject
    >;
  };
}
