/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PatientRegistry {
  export type PatientStruct = {
    patientIdHash: BytesLike;
    registrationTime: BigNumberish;
    registeredBy: AddressLike;
    isActive: boolean;
  };

  export type PatientStructOutput = [
    patientIdHash: string,
    registrationTime: bigint,
    registeredBy: string,
    isActive: boolean
  ] & {
    patientIdHash: string;
    registrationTime: bigint;
    registeredBy: string;
    isActive: boolean;
  };
}

export interface PatientRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deactivatePatient"
      | "getPatient"
      | "isPatientRegistered"
      | "patientExists"
      | "patients"
      | "registerPatient"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "PatientDeactivated" | "PatientRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deactivatePatient",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPatient",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPatientRegistered",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "patientExists",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "patients", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "registerPatient",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "deactivatePatient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPatient", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isPatientRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "patientExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "patients", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerPatient",
    data: BytesLike
  ): Result;
}

export namespace PatientDeactivatedEvent {
  export type InputTuple = [patientIdHash: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [patientIdHash: string, timestamp: bigint];
  export interface OutputObject {
    patientIdHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PatientRegisteredEvent {
  export type InputTuple = [
    patientIdHash: BytesLike,
    timestamp: BigNumberish,
    registeredBy: AddressLike
  ];
  export type OutputTuple = [
    patientIdHash: string,
    timestamp: bigint,
    registeredBy: string
  ];
  export interface OutputObject {
    patientIdHash: string;
    timestamp: bigint;
    registeredBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PatientRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): PatientRegistry;
  waitForDeployment(): Promise<this>;

  interface: PatientRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deactivatePatient: TypedContractMethod<
    [patientIdHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getPatient: TypedContractMethod<
    [patientIdHash: BytesLike],
    [PatientRegistry.PatientStructOutput],
    "view"
  >;

  isPatientRegistered: TypedContractMethod<
    [patientIdHash: BytesLike],
    [boolean],
    "view"
  >;

  patientExists: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  patients: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, string, boolean] & {
        patientIdHash: string;
        registrationTime: bigint;
        registeredBy: string;
        isActive: boolean;
      }
    ],
    "view"
  >;

  registerPatient: TypedContractMethod<
    [patientIdHash: BytesLike],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deactivatePatient"
  ): TypedContractMethod<[patientIdHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getPatient"
  ): TypedContractMethod<
    [patientIdHash: BytesLike],
    [PatientRegistry.PatientStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isPatientRegistered"
  ): TypedContractMethod<[patientIdHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "patientExists"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "patients"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, string, boolean] & {
        patientIdHash: string;
        registrationTime: bigint;
        registeredBy: string;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerPatient"
  ): TypedContractMethod<[patientIdHash: BytesLike], [boolean], "nonpayable">;

  getEvent(
    key: "PatientDeactivated"
  ): TypedContractEvent<
    PatientDeactivatedEvent.InputTuple,
    PatientDeactivatedEvent.OutputTuple,
    PatientDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "PatientRegistered"
  ): TypedContractEvent<
    PatientRegisteredEvent.InputTuple,
    PatientRegisteredEvent.OutputTuple,
    PatientRegisteredEvent.OutputObject
  >;

  filters: {
    "PatientDeactivated(bytes32,uint256)": TypedContractEvent<
      PatientDeactivatedEvent.InputTuple,
      PatientDeactivatedEvent.OutputTuple,
      PatientDeactivatedEvent.OutputObject
    >;
    PatientDeactivated: TypedContractEvent<
      PatientDeactivatedEvent.InputTuple,
      PatientDeactivatedEvent.OutputTuple,
      PatientDeactivatedEvent.OutputObject
    >;

    "PatientRegistered(bytes32,uint256,address)": TypedContractEvent<
      PatientRegisteredEvent.InputTuple,
      PatientRegisteredEvent.OutputTuple,
      PatientRegisteredEvent.OutputObject
    >;
    PatientRegistered: TypedContractEvent<
      PatientRegisteredEvent.InputTuple,
      PatientRegisteredEvent.OutputTuple,
      PatientRegisteredEvent.OutputObject
    >;
  };
}
